# Nome do Workflow
name: Build Windows Executable
# Gatilhos
on:
  push:
    branches: [ main ]
  workflow_dispatch:
# Jobs
jobs:
  build:
    runs-on: windows-latest
    steps:
    # 1. Checkout
    - name: Checkout repository code
      uses: actions/checkout@v3
    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    # 4. Build executable
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name ofxcel ofxcel.py
    # 5. Create release package
    - name: Create release package
      shell: cmd
      run: |
        mkdir release
        mkdir release\ofx
        mkdir release\excel
        copy dist\ofxcel.exe release\
        copy converter.bat release\
        copy GUIAWindows.md release\
    # 6. Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ofxcel-windows
        path: release
